
${CVA_PATH}/core/include/config_pkg.sv
${CVA_PATH}/core/include/cva6_cheri_pkg.sv
${CVA_PATH}/core/include/cv64a6_imafdc_sv39_config_pkg.sv
${CVA_PATH}/core/include/riscv_pkg.sv
${CVA_PATH}/core/include/build_config_pkg.sv
${CVA_PATH}/vendor/pulp-platform/common_cells/src/lzc.sv
${CVA_PATH}/core/cvfpu/src/common_cells/src/lfsr.sv
${CVA_PATH}/vendor/pulp-platform/common_cells/src/cf_math_pkg.sv
${CVA_PATH}/core/include/ariane_pkg.sv
${CVA_PATH}/core/pmp/src/pmp_entry.sv
${CVA_PATH}/core/pmp/src/pmp.sv
${CVA_PATH}/core/cva6_mmu/cva6_ptw.sv
${CVA_PATH}/core/cva6_mmu/cva6_shared_tlb.sv
${CVA_PATH}/core/cva6_mmu/cva6_tlb.sv
${CVA_PATH}/core/cva6_mmu/cva6_mmu.sv
${SVA_ROOT}/mmu/sva/mmu_live_sva.sv
${SVA_ROOT}/mmu/sva/mmu_sva.sv
${SVA_ROOT}/mmu/wrappers/mmu_wrapper.sv
